### PR TITLE
Add MaxBlurPool2d entry for 128

### PR DESCRIPTION
**Pull request by ducha-aiki**
unchange(Ranger-MiSH) + small change to mxresnet:  MaxBlurPool2d  insteal of AvgPool2d.
I report median(5 runs)

### CODE REVIEW

**Comment by jph00** [comment]
Sorry I missed this before I just replaced the leaderboard. Is this on the new dataset or the old one? If the new one, can you resubmit or resolve the conflict?

If the old one, can you re-run it?

Thanks a lot for this very interesting entry. It would be interesting to try 20 epochs too and see if you still get good results.

**Comment by ducha-aiki** [comment]
Sure I can run longer, will do tomorrow.
I don't know if it was old one or new - I run it yesterday in fastai v1 it was downloading it from website.

**Comment by jph00** [comment]
OK, if you have the latest fastai v1 version, then it'll be the new dataset. You should double-check that `untar_data(URLs.IMAGENETTE)` returns `~/.fastai/data/imagenette2` (i.e. that there's a "2" on the end).

**Comment by jph00** [comment]
Oh BTW please at-mention me in PRs so I get notified.

**Pull request closed without merging**
